name: Push to PyPI

on:
  push:
    tags: ["v*"]

jobs:
  python-library:
    name: Release Python library
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: library/python.build/dist
