name: Push to PyPI

on:
  push:
    tags: ["v*"]

  python-library:
    name: Release Python library
    runs-on: ubuntu-22.04
    if: needs.check-version.outputs.release == 'yes'
    permissions:
      id-token: write
    needs:
      - check-version
    steps:
      - uses: actions/checkout@v4

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: library/python.build/dist
        if: needs.check-version.outputs.release == 'yes'
